import React from 'react';
import { Download } from 'lucide-react';

export default function CharacterGrid({ baseImage, characterTag, characterName }) {
  const handleDownload = () => {
    const a = document.createElement('a');
    a.href = baseImage;
    a.download = characterTag
      ? `${characterTag}-character-sheet.png`
      : 'chibi-character-sheet.png';
    a.click();
  };

  return (
    <div className="glass-panel animate-slide-up" style={{ animationDelay: '0.2s', margin: '2rem 0' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem', flexWrap: 'wrap', gap: '0.75rem' }}>
        <div>
          <h2 style={{ fontSize: '2rem', marginBottom: '0.25rem' }}>
            {characterName
              ? <>{characterName} <span style={{ color: 'var(--accent)', fontSize: '1.1rem' }}>@{characterTag}</span></>
              : 'Character Sheet'
            }
          </h2>
          <p style={{ color: 'var(--text-muted)' }}>
            9-grid persona — generated by Nano Banana Pro.
          </p>
        </div>
        <button className="btn-secondary" onClick={handleDownload}>
          <Download size={18} style={{ marginRight: '8px' }} />
          Download
        </button>
      </div>

      <div style={{ borderRadius: 'var(--radius-sm)', overflow: 'hidden', border: '1px solid var(--glass-border)' }}>
        <img
          src={baseImage}
          alt={characterName ? `${characterName} character sheet` : 'Chibi character sheet'}
          style={{ width: '100%', display: 'block' }}
        />
      </div>
    </div>
  );
}
